[workspace]

members = [
    "formats",
    "interpreters",
    "runners",
    "utils",
]

[patch.crates-io]
touhou-formats = { path = "formats" }
touhou-interpreters = { path = "interpreters" }
touhou-runners = { path = "runners" }
touhou-utils = { path = "utils" }
